// source: services/heatmap/heatmap.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.heatmap.HeatmapPoint', null, global);
goog.exportSymbol('proto.heatmap.HeatmapRequest', null, global);
goog.exportSymbol('proto.heatmap.HeatmapResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.heatmap.HeatmapRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.heatmap.HeatmapRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.heatmap.HeatmapRequest.displayName = 'proto.heatmap.HeatmapRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.heatmap.HeatmapPoint = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.heatmap.HeatmapPoint, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.heatmap.HeatmapPoint.displayName = 'proto.heatmap.HeatmapPoint';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.heatmap.HeatmapResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.heatmap.HeatmapResponse.repeatedFields_, null);
};
goog.inherits(proto.heatmap.HeatmapResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.heatmap.HeatmapResponse.displayName = 'proto.heatmap.HeatmapResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.heatmap.HeatmapRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.heatmap.HeatmapRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.heatmap.HeatmapRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heatmap.HeatmapRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    player: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.heatmap.HeatmapRequest}
 */
proto.heatmap.HeatmapRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.heatmap.HeatmapRequest;
  return proto.heatmap.HeatmapRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.heatmap.HeatmapRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.heatmap.HeatmapRequest}
 */
proto.heatmap.HeatmapRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlayer(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.heatmap.HeatmapRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.heatmap.HeatmapRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.heatmap.HeatmapRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heatmap.HeatmapRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPlayer();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string player = 1;
 * @return {string}
 */
proto.heatmap.HeatmapRequest.prototype.getPlayer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.heatmap.HeatmapRequest} returns this
 */
proto.heatmap.HeatmapRequest.prototype.setPlayer = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.heatmap.HeatmapPoint.prototype.toObject = function(opt_includeInstance) {
  return proto.heatmap.HeatmapPoint.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.heatmap.HeatmapPoint} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heatmap.HeatmapPoint.toObject = function(includeInstance, msg) {
  var f, obj = {
    x: jspb.Message.getFloatingPointFieldWithDefault(msg, 1, 0.0),
    y: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.heatmap.HeatmapPoint}
 */
proto.heatmap.HeatmapPoint.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.heatmap.HeatmapPoint;
  return proto.heatmap.HeatmapPoint.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.heatmap.HeatmapPoint} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.heatmap.HeatmapPoint}
 */
proto.heatmap.HeatmapPoint.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setX(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setY(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.heatmap.HeatmapPoint.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.heatmap.HeatmapPoint.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.heatmap.HeatmapPoint} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heatmap.HeatmapPoint.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getX();
  if (f !== 0.0) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getY();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
};


/**
 * optional double X = 1;
 * @return {number}
 */
proto.heatmap.HeatmapPoint.prototype.getX = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.heatmap.HeatmapPoint} returns this
 */
proto.heatmap.HeatmapPoint.prototype.setX = function(value) {
  return jspb.Message.setProto3FloatField(this, 1, value);
};


/**
 * optional double Y = 2;
 * @return {number}
 */
proto.heatmap.HeatmapPoint.prototype.getY = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.heatmap.HeatmapPoint} returns this
 */
proto.heatmap.HeatmapPoint.prototype.setY = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.heatmap.HeatmapResponse.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.heatmap.HeatmapResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.heatmap.HeatmapResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.heatmap.HeatmapResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heatmap.HeatmapResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    killList: jspb.Message.toObjectList(msg.getKillList(),
    proto.heatmap.HeatmapPoint.toObject, includeInstance),
    deathList: jspb.Message.toObjectList(msg.getDeathList(),
    proto.heatmap.HeatmapPoint.toObject, includeInstance),
    bombPlantList: jspb.Message.toObjectList(msg.getBombPlantList(),
    proto.heatmap.HeatmapPoint.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.heatmap.HeatmapResponse}
 */
proto.heatmap.HeatmapResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.heatmap.HeatmapResponse;
  return proto.heatmap.HeatmapResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.heatmap.HeatmapResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.heatmap.HeatmapResponse}
 */
proto.heatmap.HeatmapResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.heatmap.HeatmapPoint;
      reader.readMessage(value,proto.heatmap.HeatmapPoint.deserializeBinaryFromReader);
      msg.addKill(value);
      break;
    case 2:
      var value = new proto.heatmap.HeatmapPoint;
      reader.readMessage(value,proto.heatmap.HeatmapPoint.deserializeBinaryFromReader);
      msg.addDeath(value);
      break;
    case 3:
      var value = new proto.heatmap.HeatmapPoint;
      reader.readMessage(value,proto.heatmap.HeatmapPoint.deserializeBinaryFromReader);
      msg.addBombPlant(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.heatmap.HeatmapResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.heatmap.HeatmapResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.heatmap.HeatmapResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.heatmap.HeatmapResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getKillList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.heatmap.HeatmapPoint.serializeBinaryToWriter
    );
  }
  f = message.getDeathList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.heatmap.HeatmapPoint.serializeBinaryToWriter
    );
  }
  f = message.getBombPlantList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.heatmap.HeatmapPoint.serializeBinaryToWriter
    );
  }
};


/**
 * repeated HeatmapPoint kill = 1;
 * @return {!Array<!proto.heatmap.HeatmapPoint>}
 */
proto.heatmap.HeatmapResponse.prototype.getKillList = function() {
  return /** @type{!Array<!proto.heatmap.HeatmapPoint>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.heatmap.HeatmapPoint, 1));
};


/**
 * @param {!Array<!proto.heatmap.HeatmapPoint>} value
 * @return {!proto.heatmap.HeatmapResponse} returns this
*/
proto.heatmap.HeatmapResponse.prototype.setKillList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.heatmap.HeatmapPoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.heatmap.HeatmapPoint}
 */
proto.heatmap.HeatmapResponse.prototype.addKill = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.heatmap.HeatmapPoint, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.heatmap.HeatmapResponse} returns this
 */
proto.heatmap.HeatmapResponse.prototype.clearKillList = function() {
  return this.setKillList([]);
};


/**
 * repeated HeatmapPoint death = 2;
 * @return {!Array<!proto.heatmap.HeatmapPoint>}
 */
proto.heatmap.HeatmapResponse.prototype.getDeathList = function() {
  return /** @type{!Array<!proto.heatmap.HeatmapPoint>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.heatmap.HeatmapPoint, 2));
};


/**
 * @param {!Array<!proto.heatmap.HeatmapPoint>} value
 * @return {!proto.heatmap.HeatmapResponse} returns this
*/
proto.heatmap.HeatmapResponse.prototype.setDeathList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.heatmap.HeatmapPoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.heatmap.HeatmapPoint}
 */
proto.heatmap.HeatmapResponse.prototype.addDeath = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.heatmap.HeatmapPoint, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.heatmap.HeatmapResponse} returns this
 */
proto.heatmap.HeatmapResponse.prototype.clearDeathList = function() {
  return this.setDeathList([]);
};


/**
 * repeated HeatmapPoint bomb_plant = 3;
 * @return {!Array<!proto.heatmap.HeatmapPoint>}
 */
proto.heatmap.HeatmapResponse.prototype.getBombPlantList = function() {
  return /** @type{!Array<!proto.heatmap.HeatmapPoint>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.heatmap.HeatmapPoint, 3));
};


/**
 * @param {!Array<!proto.heatmap.HeatmapPoint>} value
 * @return {!proto.heatmap.HeatmapResponse} returns this
*/
proto.heatmap.HeatmapResponse.prototype.setBombPlantList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.heatmap.HeatmapPoint=} opt_value
 * @param {number=} opt_index
 * @return {!proto.heatmap.HeatmapPoint}
 */
proto.heatmap.HeatmapResponse.prototype.addBombPlant = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.heatmap.HeatmapPoint, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.heatmap.HeatmapResponse} returns this
 */
proto.heatmap.HeatmapResponse.prototype.clearBombPlantList = function() {
  return this.setBombPlantList([]);
};


goog.object.extend(exports, proto.heatmap);
