// source: services/stats_summary/damage_summary/damage_summary.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.damage_summary.AllDamageSummaries', null, global);
goog.exportSymbol('proto.damage_summary.DamageSummary', null, global);
goog.exportSymbol('proto.damage_summary.DamageSummaryItem', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.damage_summary.DamageSummaryItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.damage_summary.DamageSummaryItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.damage_summary.DamageSummaryItem.displayName = 'proto.damage_summary.DamageSummaryItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.damage_summary.DamageSummary = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.damage_summary.DamageSummary.repeatedFields_, null);
};
goog.inherits(proto.damage_summary.DamageSummary, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.damage_summary.DamageSummary.displayName = 'proto.damage_summary.DamageSummary';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.damage_summary.AllDamageSummaries = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.damage_summary.AllDamageSummaries.repeatedFields_, null);
};
goog.inherits(proto.damage_summary.AllDamageSummaries, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.damage_summary.AllDamageSummaries.displayName = 'proto.damage_summary.AllDamageSummaries';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.damage_summary.DamageSummaryItem.prototype.toObject = function(opt_includeInstance) {
  return proto.damage_summary.DamageSummaryItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.damage_summary.DamageSummaryItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.damage_summary.DamageSummaryItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    given: jspb.Message.getFieldWithDefault(msg, 2, 0),
    taken: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.damage_summary.DamageSummaryItem}
 */
proto.damage_summary.DamageSummaryItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.damage_summary.DamageSummaryItem;
  return proto.damage_summary.DamageSummaryItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.damage_summary.DamageSummaryItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.damage_summary.DamageSummaryItem}
 */
proto.damage_summary.DamageSummaryItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setGiven(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTaken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.damage_summary.DamageSummaryItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.damage_summary.DamageSummaryItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.damage_summary.DamageSummaryItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.damage_summary.DamageSummaryItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getGiven();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getTaken();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.damage_summary.DamageSummaryItem.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.damage_summary.DamageSummaryItem} returns this
 */
proto.damage_summary.DamageSummaryItem.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 given = 2;
 * @return {number}
 */
proto.damage_summary.DamageSummaryItem.prototype.getGiven = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.damage_summary.DamageSummaryItem} returns this
 */
proto.damage_summary.DamageSummaryItem.prototype.setGiven = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 taken = 3;
 * @return {number}
 */
proto.damage_summary.DamageSummaryItem.prototype.getTaken = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.damage_summary.DamageSummaryItem} returns this
 */
proto.damage_summary.DamageSummaryItem.prototype.setTaken = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.damage_summary.DamageSummary.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.damage_summary.DamageSummary.prototype.toObject = function(opt_includeInstance) {
  return proto.damage_summary.DamageSummary.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.damage_summary.DamageSummary} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.damage_summary.DamageSummary.toObject = function(includeInstance, msg) {
  var f, obj = {
    category: jspb.Message.getFieldWithDefault(msg, 1, ""),
    itemsList: jspb.Message.toObjectList(msg.getItemsList(),
    proto.damage_summary.DamageSummaryItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.damage_summary.DamageSummary}
 */
proto.damage_summary.DamageSummary.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.damage_summary.DamageSummary;
  return proto.damage_summary.DamageSummary.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.damage_summary.DamageSummary} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.damage_summary.DamageSummary}
 */
proto.damage_summary.DamageSummary.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategory(value);
      break;
    case 2:
      var value = new proto.damage_summary.DamageSummaryItem;
      reader.readMessage(value,proto.damage_summary.DamageSummaryItem.deserializeBinaryFromReader);
      msg.addItems(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.damage_summary.DamageSummary.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.damage_summary.DamageSummary.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.damage_summary.DamageSummary} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.damage_summary.DamageSummary.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCategory();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getItemsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.damage_summary.DamageSummaryItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional string category = 1;
 * @return {string}
 */
proto.damage_summary.DamageSummary.prototype.getCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.damage_summary.DamageSummary} returns this
 */
proto.damage_summary.DamageSummary.prototype.setCategory = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * repeated DamageSummaryItem items = 2;
 * @return {!Array<!proto.damage_summary.DamageSummaryItem>}
 */
proto.damage_summary.DamageSummary.prototype.getItemsList = function() {
  return /** @type{!Array<!proto.damage_summary.DamageSummaryItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.damage_summary.DamageSummaryItem, 2));
};


/**
 * @param {!Array<!proto.damage_summary.DamageSummaryItem>} value
 * @return {!proto.damage_summary.DamageSummary} returns this
*/
proto.damage_summary.DamageSummary.prototype.setItemsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.damage_summary.DamageSummaryItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.damage_summary.DamageSummaryItem}
 */
proto.damage_summary.DamageSummary.prototype.addItems = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.damage_summary.DamageSummaryItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.damage_summary.DamageSummary} returns this
 */
proto.damage_summary.DamageSummary.prototype.clearItemsList = function() {
  return this.setItemsList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.damage_summary.AllDamageSummaries.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.damage_summary.AllDamageSummaries.prototype.toObject = function(opt_includeInstance) {
  return proto.damage_summary.AllDamageSummaries.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.damage_summary.AllDamageSummaries} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.damage_summary.AllDamageSummaries.toObject = function(includeInstance, msg) {
  var f, obj = {
    dataList: jspb.Message.toObjectList(msg.getDataList(),
    proto.damage_summary.DamageSummary.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.damage_summary.AllDamageSummaries}
 */
proto.damage_summary.AllDamageSummaries.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.damage_summary.AllDamageSummaries;
  return proto.damage_summary.AllDamageSummaries.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.damage_summary.AllDamageSummaries} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.damage_summary.AllDamageSummaries}
 */
proto.damage_summary.AllDamageSummaries.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.damage_summary.DamageSummary;
      reader.readMessage(value,proto.damage_summary.DamageSummary.deserializeBinaryFromReader);
      msg.addData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.damage_summary.AllDamageSummaries.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.damage_summary.AllDamageSummaries.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.damage_summary.AllDamageSummaries} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.damage_summary.AllDamageSummaries.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDataList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.damage_summary.DamageSummary.serializeBinaryToWriter
    );
  }
};


/**
 * repeated DamageSummary data = 1;
 * @return {!Array<!proto.damage_summary.DamageSummary>}
 */
proto.damage_summary.AllDamageSummaries.prototype.getDataList = function() {
  return /** @type{!Array<!proto.damage_summary.DamageSummary>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.damage_summary.DamageSummary, 1));
};


/**
 * @param {!Array<!proto.damage_summary.DamageSummary>} value
 * @return {!proto.damage_summary.AllDamageSummaries} returns this
*/
proto.damage_summary.AllDamageSummaries.prototype.setDataList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.damage_summary.DamageSummary=} opt_value
 * @param {number=} opt_index
 * @return {!proto.damage_summary.DamageSummary}
 */
proto.damage_summary.AllDamageSummaries.prototype.addData = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.damage_summary.DamageSummary, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.damage_summary.AllDamageSummaries} returns this
 */
proto.damage_summary.AllDamageSummaries.prototype.clearDataList = function() {
  return this.setDataList([]);
};


goog.object.extend(exports, proto.damage_summary);
